# Telegram
TELEGRAM_TOKEN = ""

# Model
START_USER_MESSAGE = ""
SYSTEM_MESSAGE = """You are a bot
{0}
"""


BASE_LANGUAGE = "en"

# Ollama
OLLAMA_API_HOST = "http://localhost:11434"
OLLAMA_MODEL = "llama2:13b-chat"
OLLAMA_MODEL_TEMPERATURE = 1
OLLAMA_KEEP_ALIVE = "5m"
# TODO: OLLAMA_INSTALL_MISSING_MODELS
